#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g angular-cli
  - npm install -g firebase-bolt
  - pushd $TRAVIS_BUILD_DIR/functions && npm install && popd

script:
  - ng build --prod
  - firebase-bolt database.rules.bolt

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      firebase deploy --token $FIREBASE_TOKEN;
    fi;

notifications:
  email:
    on_failure: always
    on_success: change
